services:
  pgadmin:
    image: dpage/pgadmin4:latest
    logging:
      options:
        max-size: "50m"
    container_name: pgAdminSQL
    restart: unless-stopped
    depends_on:
      - dbPostgreSQL
    env_file:
      - .env
    ports:
      - 8008:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    networks:
      - pgNetwork
    # Limites de recursos para uso local
    cpus: "1.0"
    mem_limit: 256m

volumes:
  pgadmin: