services:
  pgsql:
    image: postgres
    logging:
      options:
        max-size: "50m"
    container_name: dbPostgreSQL
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data/pgsql:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - pgNetwork

volumes:
  pgsql:

networks:
  pgNetwork:
    name: pgNetwork
    external: true